.TH SIEMMANAGE 1
.SH NAME
siemmanage - CLI tool for managing SIEM tables

.SH SYNOPSIS

\fBsiemmanage\fR [\fB-h] [\fB--version\fR] [\fB-c \fICONFIG\fR] [\fB--clear\fR] [\fB--force\fR] [\fB--importrules \fIFILE\fR] [\fB--exportrules \fIFILE\fR] [\fB--imporhelpers \fIFILE\fR] [\fB--exporthelpers \fIFILE\fR] [\fB--table \fITABLE\fR]

.SH DESCRIPTION
\fBsiemmanage\fR is a tool for clearing SIEM tables, and importing and exporting rules and helpers.

.SH OPTIONS
  
  usage: \fBsiemtrigger\fR [\fBoptions\fR]

  optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -c CONFIG             set the config file
  --clear               delete the SQL table for selected section
  --force               really delete the table
  --importrules FILE    set a JSON file to import rules
  --exportrules FILE    set a JSON file to export rules
  --importhelpers FILE  set a JSON file to import helpers
  --exporthelpers FILE  set a JSON file to export helpers
  --table TABLE         set a table

.SH EXAMPLES
    siemmanage --importhelpers config/example_helpers.json
    siemmanage --exportfules rules.json --table RULESAuth
    siemmanage --clear --force --table Auth

.SH SEE ALSO
    siemcli(7)
    siemparse(1)
    siemquery(1)
    siemtrigger(1)

.SH FILES
    /etc/siemcli/db.conf
    /etc/siemcli/sections.conf
    /usr/share/doc/siemcli/README.md
    /usr/share/doc/siemcli/LICENSE
    /usr/share/doc/siemcli/CHANGELOG.md

  
 
