.TH siemcli 7
.SH NAME
siemcli - a CLI based Security Information and Event Management (SIEM) system

.SH DESCRIPTION
\fBsiemcli\fR is a suite of CLI tools for managing log events, and automating event analysis. It comes with four programs: siemparse, siemquery, siemtrigger, and siemmanage.

\fBsiemparse\fR is a CLI tool to parse syslog lines from standard input into a siemcli database.

\fBsiemquery\fR is a CLI tool to query a siemcli database.

\fBsiemtrigger\fR is a CLI tool to trigger SIEM events based on siemcli database analysis.

\fBsiemmanage\fR is a CLI tool to manage SIEM tables.

.SH SEE ALSO
    siemparse(1)
    siemquery(1)
    siemtrigger(1)
    siemmanage(1)

.SH FILES
    /etc/siemcli/db.conf
    /etc/siemcli/sections.conf
    /usr/share/doc/siemcli/example_rules.json
    /usr/share/doc/siemcli/example_helpers.json
    /usr/share/doc/siemcli/README.md
    /usr/share/doc/siemcli/LICENSE
    /usr/share/doc/siemcli/CHANGELOG.md

  
 
